# Site settings
title: 灰度blog
email: liyaozong1991@gmail.com
description: 用文字见证成长
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: liyaozong1991
# permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/liyaozong1991/liyaozong1991.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/liyaozong1991/liyaozong1991.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com.
duoshuo_shortname: liyaozong1991
duoshuo_url: "https://liyaozong1991.github.io"
#########################################

#theme: monophase
theme_dir: _themes/monophase

paginate: 10
paginate_path: "page:num"
# gems: [jekyll-paginate]

# Build settings
markdown: kramdown
#kramdown:
#  input: GFM

# highlight
# highlighter: pygments
highlighter: rouge
encoding: utf-8
#highlighter: true

#theme: jekyll-theme-merlot


incremental: false # 禁止使用增量构建

